Revert "Adopt eslint's no-prototype-builtins rule."
This reverts commit b184a939902a1ac0061234f5bae1db53b72d03fa.

This broke LDAP, causing errors like:

```
Exception while invoking method 'login' TypeError: hasOwnProperty is not a function
    at LDAP.ldapCheck (imports/server/accounts/ldap.js:49:8)
    at MethodInvocation.<anonymous> (imports/server/accounts/ldap/ldap-server.js:25:30)
    at packages/accounts-base/accounts_server.js:462:31
    at tryLoginMethod (packages/accounts-base/accounts_server.js:1291:14)
    at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:460:22)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:31)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```